# Logistic Regression Implementation

In [48]:
from sklearn.datasets import load_iris
dataset=load_iris()
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [49]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [51]:
import pandas as pd
import numpy as np
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [52]:
print(dataset.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [53]:
df['target']=dataset.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [54]:
df['target'].unique()

array([0, 1, 2])

# Binary Classification

In [55]:
df[df['target']!=2]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
95       1  
96       1  
97       1  
98       1  
99       1  

[100 rows x 5 columns]

In [56]:
df_copy=df[df['target']!=2]

In [57]:
df_copy['target'].unique()

array([0, 1])

In [64]:
X = df_copy.drop(columns="target")
y = df_copy['target']

In [65]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [66]:
from sklearn.linear_model import LogisticRegression
classification = LogisticRegression(max_iter=200)
classification

LogisticRegression(max_iter=200)

In [67]:
classification.fit(X_train, y_train)

LogisticRegression(max_iter=200)

In [68]:
y_pred = classification.predict(X_test)

In [69]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

# Confusion metrics, accuracy, classification report

In [70]:
from sklearn.metrics import  confusion_matrix, accuracy_score, classification_report
print(confusion_matrix(y_test, y_pred))

[[12  0]
 [ 0  8]]


In [72]:
print(accuracy_score(y_test, y_pred))

1.0


In [73]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [77]:
from sklearn.model_selection import KFold

In [79]:
crossvalidation = KFold(n_splits=5)
crossvalidation

KFold(n_splits=5, random_state=None, shuffle=False)

In [81]:
# for binary classification scoring = 'accuracy'
from sklearn.model_selection import cross_val_score
scores = cross_val_score(classification, X_train, y_train, scoring='accuracy', cv=crossvalidation)
# these are scores after every experiment
scores

array([1., 1., 1., 1., 1.])

In [82]:
accuracy = np.mean(scores)
accuracy

1.0

# Another example

In [83]:
## Lets see more complex data

# make a prediction logistic regression model
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=2, random_state=1)

In [85]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [86]:
from sklearn.linear_model import LogisticRegression
complex_classification = LogisticRegression(max_iter=200)
complex_classification

LogisticRegression(max_iter=200)

In [87]:
complex_classification.fit(X_train, y_train)

LogisticRegression(max_iter=200)

In [88]:
y_pred_complex = complex_classification.predict(X_test)

In [89]:
print(confusion_matrix(y_test, y_pred_complex))
print(accuracy_score(y_test, y_pred_complex))
print(classification_report(y_test, y_pred_complex))

[[78 13]
 [29 80]]
0.79
              precision    recall  f1-score   support

           0       0.73      0.86      0.79        91
           1       0.86      0.73      0.79       109

    accuracy                           0.79       200
   macro avg       0.79      0.80      0.79       200
weighted avg       0.80      0.79      0.79       200



# Cross validation on complex dataset

In [90]:
crossvalidation = KFold(n_splits=5)
scores = cross_val_score(complex_classification, X_train, y_train, cv = crossvalidation)
scores

array([0.80625, 0.78125, 0.79375, 0.8125 , 0.85625])

In [92]:
accuracy = np.mean(scores)
accuracy

0.8099999999999999

To stakeholders, we should not say one value of accuracy.

You should say that we got max acc = 85, min acc = 78, avg acc = 80 with some + or -

Cross validation is a simple way to internally divide training dataset to train and validation data. We find out with a particular seperation, what accuracy you get.

Reading Documentation is important