In [3]:
import numpy as np
myList = ['1', '2', '3', '4', '5']
array_myList = np.array(object = myList)

# Question 1

Yes there is a difference in the datatypes of 2 variables.

In [4]:
print(type(myList), type(array_myList))

<class 'list'> <class 'numpy.ndarray'>


# Question 2

 Write a code to print the data type of each and every element of both the variables myList and
array_myList

In [7]:
for i in myList :
    print(i, type(i))

print("\n")

for i in array_myList :
    print(i, type(i))

1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>


1 <class 'numpy.str_'>
2 <class 'numpy.str_'>
3 <class 'numpy.str_'>
4 <class 'numpy.str_'>
5 <class 'numpy.str_'>


# Question 3
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, myList
and array_myList.

In [9]:
array_myList = np.array(object = myList, dtype = int)
print(type(array_myList))
for i in array_myList :
    print(i, type(i))

<class 'numpy.ndarray'>
1 <class 'numpy.int64'>
2 <class 'numpy.int64'>
3 <class 'numpy.int64'>
4 <class 'numpy.int64'>
5 <class 'numpy.int64'>


# Next section

In [10]:
import numpy as np
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object = num_list)

# Question 4

In [11]:
print(f"shape = {num_array.shape}\n size = {num_array.size}")

shape = (2, 3)
 size = 6


# Question 5
Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [14]:
created_array = np.random.randint(0, 1, (3, 3))
print(created_array)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


# Question 6
 Create an identity matrix of shape (5,5) using numpy functions?

In [17]:
id_mat = np.diag([1, 1, 1, 1, 1])
print(id_mat)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
