In [1]:
import numpy as np

In [3]:
# Numpy - array manipulation
arr = np.random.randint(1, 10, (4, 4))

In [4]:
arr

array([[5, 1, 8, 1],
       [6, 5, 4, 2],
       [5, 6, 4, 8],
       [6, 8, 7, 6]])

In [5]:
# reshaping
arr.reshape(8, 2)

array([[5, 1],
       [8, 1],
       [6, 5],
       [4, 2],
       [5, 6],
       [4, 8],
       [6, 8],
       [7, 6]])

In [6]:
# transpose of array
arr.T

array([[5, 6, 5, 6],
       [1, 5, 6, 8],
       [8, 4, 4, 7],
       [1, 2, 8, 6]])

In [7]:
# conversion of n D array to 1 D array
arr.flatten()

array([5, 1, 8, 1, 6, 5, 4, 2, 5, 6, 4, 8, 6, 8, 7, 6])

In [8]:
arr

array([[5, 1, 8, 1],
       [6, 5, 4, 2],
       [5, 6, 4, 8],
       [6, 8, 7, 6]])

In [11]:
"""
expansion of dimension by 1
Conversion of 2 D array to 3 D array
axis = 0 -> Rows
axis = 1 -> Columns
"""
np.expand_dims(arr, axis=0)

array([[[5, 1, 8, 1],
        [6, 5, 4, 2],
        [5, 6, 4, 8],
        [6, 8, 7, 6]]])

In [12]:
np.expand_dims(arr, axis=1)

array([[[5, 1, 8, 1]],

       [[6, 5, 4, 2]],

       [[5, 6, 4, 8]],

       [[6, 8, 7, 6]]])

In [13]:
data = np.array([[1], [2], [3]])

In [14]:
# reduction of dimension by 1
np.squeeze(data)

array([1, 2, 3])

In [15]:
# step 1 -> squeeze
# step 2 -> repeat data 2 times
np.repeat(data, 2)

array([1, 1, 2, 2, 3, 3])

In [18]:
# step 1 -> squeeze
# step 2 -> repeat data 4 times
np.repeat(data, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [20]:
# each element will jump 2 indices forward
np.roll(data, 2)

array([[2],
       [3],
       [1]])

In [21]:
data

array([[1],
       [2],
       [3]])

In [22]:
# each element will jump 2 indices forward
np.roll(data, 1)

array([[3],
       [1],
       [2]])

In [23]:
# generating a diagnol matrix
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [25]:
# Numpy - Binary operation
arr1 = np.random.randint(1, 10, (3, 4))
arr2 = np.random.randint(1, 10, (3, 4))
print(arr1)
print(arr2)

[[8 1 6 3]
 [7 2 5 9]
 [5 3 6 1]]
[[3 3 9 9]
 [3 5 4 5]
 [8 8 9 7]]


In [26]:
# Index wise addition
arr1 + arr2

array([[11,  4, 15, 12],
       [10,  7,  9, 14],
       [13, 11, 15,  8]])

In [27]:
# Index wise subtraction
arr1 - arr2

array([[ 5, -2, -3, -6],
       [ 4, -3,  1,  4],
       [-3, -5, -3, -6]])

In [29]:
# Index wise multiplication
arr1 * arr2

array([[24,  3, 54, 27],
       [21, 10, 20, 45],
       [40, 24, 54,  7]])

In [30]:
# Index wise division
arr1 / arr2

array([[2.66666667, 0.33333333, 0.66666667, 0.33333333],
       [2.33333333, 0.4       , 1.25      , 1.8       ],
       [0.625     , 0.375     , 0.66666667, 0.14285714]])

In [31]:
# Index wise power operation
arr1 ** arr2
"""
for addition            shape of both the matrices should be equal
    subtraction
    multiplication
    division
"""

array([[     512,        1, 10077696,    19683],
       [     343,       32,      625,    59049],
       [  390625,     6561, 10077696,        1]])

In [32]:
# Binary negation
~arr1

array([[ -9,  -2,  -7,  -4],
       [ -8,  -3,  -6, -10],
       [ -6,  -4,  -7,  -2]])

In [33]:
arr1 > arr2

array([[ True, False, False, False],
       [ True, False,  True,  True],
       [False, False, False, False]])

In [37]:
# Numpy - String functions
arr = np.array(["vignesh", "reddy"])
arr

array(['vignesh', 'reddy'], dtype='<U7')

In [38]:
# conversion to upper case
np.char.upper(arr)

array(['VIGNESH', 'REDDY'], dtype='<U7')

In [39]:
np.char.capitalize(arr)

array(['Vignesh', 'Reddy'], dtype='<U7')

In [40]:
# all the functions of string are in numpy char class
np.char.title(arr)

array(['Vignesh', 'Reddy'], dtype='<U7')

In [41]:
# Numpy - Mathematical functions

In [42]:
arr1

array([[8, 1, 6, 3],
       [7, 2, 5, 9],
       [5, 3, 6, 1]])

In [43]:
np.sin(arr1)

array([[ 0.98935825,  0.84147098, -0.2794155 ,  0.14112001],
       [ 0.6569866 ,  0.90929743, -0.95892427,  0.41211849],
       [-0.95892427,  0.14112001, -0.2794155 ,  0.84147098]])

In [44]:
np.cos(arr1)

array([[-0.14550003,  0.54030231,  0.96017029, -0.9899925 ],
       [ 0.75390225, -0.41614684,  0.28366219, -0.91113026],
       [ 0.28366219, -0.9899925 ,  0.96017029,  0.54030231]])

In [45]:
np.tan(arr1)

array([[-6.79971146,  1.55740772, -0.29100619, -0.14254654],
       [ 0.87144798, -2.18503986, -3.38051501, -0.45231566],
       [-3.38051501, -0.14254654, -0.29100619,  1.55740772]])

In [46]:
np.log10(arr1)

array([[0.90308999, 0.        , 0.77815125, 0.47712125],
       [0.84509804, 0.30103   , 0.69897   , 0.95424251],
       [0.69897   , 0.47712125, 0.77815125, 0.        ]])

In [47]:
np.exp(arr1)

array([[2.98095799e+03, 2.71828183e+00, 4.03428793e+02, 2.00855369e+01],
       [1.09663316e+03, 7.38905610e+00, 1.48413159e+02, 8.10308393e+03],
       [1.48413159e+02, 2.00855369e+01, 4.03428793e+02, 2.71828183e+00]])

In [48]:
np.power(arr1, 6)

array([[262144,      1,  46656,    729],
       [117649,     64,  15625, 531441],
       [ 15625,    729,  46656,      1]])

In [49]:
np.mean(arr1)

4.666666666666667

In [50]:
np.median(arr1)

5.0

In [52]:
np.std(arr1)

2.560381915956203

In [53]:
np.var(arr1)

6.555555555555556

In [54]:
np.min(arr1)

1

In [55]:
np.max(arr1)

9

In [56]:
# Numpy - arithmetic operation

In [57]:
arr1

array([[8, 1, 6, 3],
       [7, 2, 5, 9],
       [5, 3, 6, 1]])

In [58]:
arr2

array([[3, 3, 9, 9],
       [3, 5, 4, 5],
       [8, 8, 9, 7]])

In [59]:
# Binary operation
arr1 - arr2

array([[ 5, -2, -3, -6],
       [ 4, -3,  1,  4],
       [-3, -5, -3, -6]])

In [60]:
# subtract function in numpy
np.subtract(arr1, arr2)

array([[ 5, -2, -3, -6],
       [ 4, -3,  1,  4],
       [-3, -5, -3, -6]])

In [61]:
np.multiply(arr1, arr2)

array([[24,  3, 54, 27],
       [21, 10, 20, 45],
       [40, 24, 54,  7]])

In [62]:
# (Index wise element of arr1) % (Index wise element of arr2)
np.mod(arr1, arr2)

array([[2, 1, 6, 3],
       [1, 2, 1, 4],
       [5, 3, 6, 1]])

In [63]:
np.power(arr1, arr2)

array([[     512,        1, 10077696,    19683],
       [     343,       32,      625,    59049],
       [  390625,     6561, 10077696,        1]])

In [64]:
# Numpy Statistical function
arr1

array([[8, 1, 6, 3],
       [7, 2, 5, 9],
       [5, 3, 6, 1]])

In [66]:
np.mean(arr1)

4.666666666666667

In [67]:
np.std(arr1)

2.560381915956203

In [68]:
np.median(arr1)

5.0