In [1]:
print("Hello world")

Hello world


In [2]:
import numpy as np
# numpy is used for array and matrix based calculations

In [14]:
# list to numpy array
List = [1, 2, 3, 4]
arr = np.array(List)
print(arr)

[1 2 3 4]


In [15]:
type(arr)

numpy.ndarray

In [16]:
# alternative way for list to numpy array
np.asarray(List)

array([1, 2, 3, 4])

In [17]:
# creating a 2D array
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)
print(arr1.ndim)

1
2


In [19]:
# exploring matrix attribute
# it will always create a matrix
np.matrix(List)

matrix([[1, 2, 3, 4]])

In [20]:
mat = np.matrix(List)

In [21]:
mat.ndim

2

In [11]:
np.matrix(mat)

matrix([[1, 2, 3, 4]])

In [12]:
# exploring asanyarray attribute
np.asanyarray(List)
# it has converted a list into an array

array([1, 2, 3, 4])

In [13]:
# if we pass mat, then there will be no changes in mat
np.asanyarray(mat)
"""
it is a function which will be able to convert anything into array if initially it is not available in any form of array
since matrix is a sub class of array 
therefore there are no changes
"""


matrix([[1, 2, 3, 4]])

In [22]:
# in memory arr is pointing to [1, 2, 3, 4]
arr

array([1, 2, 3, 4])

In [23]:
# in memory a is pointing to [1, 2, 3, 4]
# Both a and arr is referring to same array
a = arr

In [24]:
a

array([1, 2, 3, 4])

In [25]:
arr

array([1, 2, 3, 4])

In [26]:
# shallow copy operation
arr[0] = 100
arr

array([100,   2,   3,   4])

In [27]:
a

array([100,   2,   3,   4])

In [28]:
# deep copy
# in memory arr is pointing to [1, 2, 3, 4]
# in memory b is pointing to a new array [1, 2, 3, 4]
b = np.copy(arr)
b

array([100,   2,   3,   4])

In [30]:
b[0] = 234

In [31]:
# change
b

array([234,   2,   3,   4])

In [32]:
# no change
arr

array([100,   2,   3,   4])

In [33]:
# this function gives an array or matrix based on nature of function
np.fromfunction(lambda i, j : i == j, (3, 3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [34]:
np.fromfunction(lambda i, j : i * j, (3, 3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [37]:
# we have generated a list containing square of elements
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [38]:
# we can also generate with numpy function
iterable = list(i*i for i in range(5))

In [40]:
# this attribute has generated a array consisting of square of numbers
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

In [43]:
# genrating array from a string using seperator
np.fromstring('23 45 56', int, sep = ' ')

array([23, 45, 56])

In [44]:
np.fromstring('23,45,56', int, sep = ',')

array([23, 45, 56])

In [45]:
arr

array([100,   2,   3,   4])

In [46]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
# dimension of array = no. of brackets at end
arr.ndim

1

In [48]:
arr1.ndim

2

In [49]:
# no. of elements
arr.size

4

In [50]:
arr1.size

6

In [51]:
# shape
arr.shape

(4,)

In [52]:
arr1.shape

(2, 3)

In [53]:
# data types of element
arr.dtype

dtype('int64')

In [54]:
arr1.dtype

dtype('int64')