In [17]:
print("Hello world")

Hello world


In [18]:
import numpy as np

In [19]:
# Sort, search, counting functions
arr = np.array([4, 2, 8, 5, 3, 9, 12, 56])
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [20]:
np.sort(arr)

array([ 2,  3,  4,  5,  8,  9, 12, 56])

In [21]:
# if value is not in array then the function returns the place where it should kept so that sorted order is not disturbed
np.searchsorted(arr, 6)

5

In [22]:
# if value is in array then the function returns place of value in sorted order
np.searchsorted(arr, 8)

5

In [23]:
arr1 = np.array([0, 324, 645, 65, 6, 6, 0, 0, 0, 234])

In [24]:
np.count_nonzero(arr1)

6

In [25]:
# this function returns the indices which satisfy the condition
np.where(arr1 > 0)

(array([1, 2, 3, 4, 5, 9]),)

In [26]:
# this function returns the values in array which satisfy the condition
np.extract(arr1 > 0, arr1)

array([324, 645,  65,   6,   6, 234])

In [27]:
# Numpy - Byte Swapping
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [29]:
# this function swaps the values in array with their respective bytes
arr.byteswap()

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [30]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [31]:
# making inplace True
arr.byteswap(True)

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [32]:
arr

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [33]:
# Numpy - Copies and views
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [34]:
# deep copy
a = np.copy(arr1)

In [36]:
# shallow copy
b = arr1.view()
# the above statement is equivalent to b = arr1

In [37]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [38]:
b[0] = 234

In [39]:
b

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [40]:
arr1

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [41]:
# Numpy - Matrix Library
# whatever we have done with Numpy library, we can do that with numpy.matlib
import numpy.matlib as nm

In [43]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [45]:
nm.ones((3, 4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [46]:
# identity matrix
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [48]:
# Linear Algebra
arr1 = np.random.randint([[2, 3], [4, 5]])
arr2 = np.random.randint([[5, 3], [2, 5]])
print(arr1)
print(arr2)

[[1 0]
 [2 4]]
[[3 2]
 [0 0]]


In [49]:
# dot product of these two arrays
np.dot(arr1, arr2)

array([[3, 2],
       [6, 4]])

In [50]:
# alternative
arr1 @ arr2

array([[3, 2],
       [6, 4]])