In [1]:
print("Hello world")

Hello world


In [2]:
import numpy as np

In [3]:
list(range(0, 5))

[0, 1, 2, 3, 4]

In [4]:
# we cannot pass float values in range function
list(range(0.4, 9.6))

TypeError: 'float' object cannot be interpreted as an integer

In [5]:
# arange function of numpy can take float values
np.arange(0.4, 9.6, 0.2)

array([0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8,
       3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4,
       5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. ,
       8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4])

In [6]:
list(np.arange(0.4, 9.6, 0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004]

In [7]:
# we have genrated a data with GLB = 1 LUB = 5 and scaling distance = 20
np.linspace(1, 5, 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [9]:
# this function gives us 10 data values
# default setting -> base = 10
np.logspace(1, 5, 10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [10]:
np.logspace(1, 5, 10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [11]:
# creating an  array with all values 0
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
# creating an matrix with all values 0 and given shape 3 x 4 
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
# we generated a 3 D data set with shape 4 x 2
np.zeros((3, 4, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [16]:
np.zeros((4, 3, 2, 3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
arr = np.ones((3, 4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [21]:
arr * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [22]:
# generating empty matrix
np.empty((3, 4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [23]:
# identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
arr1 = np.eye(5)

In [28]:
# convert numpy array to data frame
import pandas as pd
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [29]:
# creating a 2 D matrix with shape 2 x 3 with random data values
# mean and standard deviation of data set can be anything
np.random.rand(2, 3)

array([[0.40660437, 0.46838993, 0.60646131],
       [0.33674879, 0.86120162, 0.82699724]])

In [30]:
# This function generates data in standard normal distribution.
# mean = 0 and standard deviation = 1
np.random.randn(2, 3)

array([[-0.29996094,  0.41018717, -0.6404167 ],
       [ 0.61870373, -0.37558201,  0.66034345]])

In [31]:
# creation of matrix between 1 and 5(excluding) with shape (3, 4)
np.random.randint(1, 5, (3, 4))

array([[4, 3, 4, 2],
       [4, 3, 2, 2],
       [1, 2, 3, 4]])

In [32]:
arr2 = np.random.randint(1, 5, (3, 4))
arr2

array([[4, 4, 1, 4],
       [3, 2, 1, 4],
       [1, 3, 2, 3]])

In [33]:
arr2.size

12

In [34]:
arr2.shape

(3, 4)

In [35]:
# Note : Whenver you are giving new shape ensure that total no. of element are equal before and after
arr2.reshape(6, 2)

array([[4, 4],
       [1, 4],
       [3, 2],
       [1, 4],
       [1, 3],
       [2, 3]])

In [36]:
arr2.reshape(6, 3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [37]:
arr2.reshape(2, 3)

ValueError: cannot reshape array of size 12 into shape (2,3)

In [38]:
# when you pass any parameter row or column negative then 
# it automatically reshapes according to either argument
arr2.reshape(4, -1)

array([[4, 4, 1],
       [4, 3, 2],
       [1, 4, 1],
       [3, 2, 3]])

In [39]:
arr2.reshape(13, -1)

ValueError: cannot reshape array of size 12 into shape (13,newaxis)

In [40]:
arr2.reshape(3, 2, 2)

array([[[4, 4],
        [1, 4]],

       [[3, 2],
        [1, 4]],

       [[1, 3],
        [2, 3]]])

In [41]:
arr1 = np.random.randint(1, 10, (5, 6))

In [42]:
arr1

array([[1, 5, 8, 9, 9, 8],
       [7, 3, 7, 3, 9, 8],
       [2, 6, 4, 8, 8, 9],
       [3, 9, 4, 5, 8, 1],
       [4, 5, 9, 3, 3, 4]])

In [43]:
# filter out data set greater than 8
arr1 > 8

array([[False, False, False,  True,  True, False],
       [False, False, False, False,  True, False],
       [False, False, False, False, False,  True],
       [False,  True, False, False, False, False],
       [False, False,  True, False, False, False]])

In [44]:
arr1[arr1 > 8]

array([9, 9, 9, 9, 9, 9])

In [45]:
# 0th row
arr1[0]

array([1, 5, 8, 9, 9, 8])

In [46]:
# 0th row
# 0th, 1st column
arr1[0,[0, 1]]

array([1, 5])

In [49]:
arr1[2 : 4, [2, 3]]

array([[4, 8],
       [4, 5]])

In [50]:
# addition - shape of matrices should be same
arr1 = np.random.randint(1, 3, (3, 3))
arr2 = np.random.randint(1, 3, (3, 3))
print(arr1)
print(arr2)
print(arr1 + arr2)

[[1 2 2]
 [1 2 2]
 [1 1 2]]
[[1 2 2]
 [2 1 1]
 [1 1 1]]
[[2 4 4]
 [3 3 3]
 [2 2 3]]


In [51]:
# subtraction - shape of matrices should be same
arr1 - arr2

array([[ 0,  0,  0],
       [-1,  1,  1],
       [ 0,  0,  1]])

In [52]:
# index wise multiplication - shape should be same
arr1 * arr2

array([[1, 4, 4],
       [2, 2, 2],
       [1, 1, 2]])

In [53]:
""" 
matrix multiplication -   matrix 1  x  matrix 2  =  resulatant 
                          (m x n)      (n x p)       (m x p)
"""
arr1 @ arr2

array([[7, 6, 6],
       [7, 6, 6],
       [5, 5, 5]])

In [54]:
# index wise division operation - shape should be same
arr1 / arr2

array([[1. , 1. , 1. ],
       [0.5, 2. , 2. ],
       [1. , 1. , 2. ]])

In [55]:
# infinity exist in numpy but in python core compiler throws an error
arr1 / 0

/tmp/ipykernel_536/824215542.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [57]:
# Numpy - Broadcasting
arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
# I am broadcasting 5 to all elements
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [60]:
(arr + 1) * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [61]:
a = np.array([1, 2, 3, 4])

In [64]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
a

array([1, 2, 3, 4])

In [66]:
# Visualize addition while revising
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [69]:
b = np.array([[3, 4, 5]])

In [70]:
# we got an error because we are adding row wise
arr + b

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [71]:
arr + b.T

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [72]:
arr1 = arr + b.T

In [73]:
# some mathematical operations
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [74]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [75]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [76]:
np.min(arr1)

3.0

In [77]:
np.max(arr1)

5.0